name: Test self hosted runner

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'


jobs:
  testing:
    name: Test runner
    runs-on: [self-hosted, Linux, X64, prod, main, test]
    steps:
        - name: Hello to runner
          run: |
            pwd
            hostname
            echo 'Hello World'

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}

        - name: Install Dependencies
          run: npm install